Repository VaibhavCodeClub/learn, pull requests merged in 2024-05, with the labels that each got.

#12 Enhance_UI
  lib/pages/atoz.dart
  pubspec.lock
Labels: GSSoC

#36 Updated README.md
  README.md
Labels: gssoc

#43 Fix issue #38
  lib/pages/parts.dart
  lib/utils/responsive_screen_provider.dart
Labels: Under Review 👀

#63 Changes to home page.
  lib/cubit/index_cubit.dart
  lib/main.dart
  lib/pages/explore.dart
  lib/pages/favorite.dart
  lib/pages/home.dart
  lib/pages/modules/animals.dart
  lib/pages/modules/atoz.dart
  lib/pages/modules/birds.dart
  lib/pages/modules/colours.dart
  lib/pages/modules/parts.dart
  lib/pages/modules/shapes.dart
  lib/pages/modules/solar.dart
  lib/utils/constants.dart
  lib/utils/routes.dart
  lib/widgets/navbar/navbar.dart
  pubspec.lock
  pubspec.yaml
Labels: gssoc, Level2

#73 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, gssoc, Level1

#100 Create CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: gssoc, level1

#101 Feature brightness button
  lib/pages/home.dart
Labels: gssoc, level1

#105 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#106 Create pull-request.md
  .github/pull-request.md
Labels: gssoc, level1

#109 Deleted the (dead code) `main` function from the `atoz.dart` file
  lib/pages/modules/atoz.dart
Labels: bug, gssoc, level1

#130 [FEAT]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc, level2

#131 Solved the issue of overflow in app drawer and about page
  lib/pages/about.dart
  lib/widgets/drawer.dart
Labels: gssoc, level1

#112 Models folder created in lib folder
  lib/models/animal_model.dart
  lib/models/bird_model.dart
  lib/models/colours_model.dart
  lib/models/flower_model.dart
  lib/models/itemdata_model.dart
  lib/models/occupation_model.dart
  lib/models/planet_model.dart
  lib/models/season_model.dart
  lib/pages/modules/animals.dart
  lib/pages/modules/atoz.dart
  lib/pages/modules/birds.dart
  lib/pages/modules/colours.dart
  lib/pages/modules/flowers.dart
  lib/pages/modules/occupation.dart
  lib/pages/modules/planets.dart
  lib/pages/modules/seasons.dart
  lib/utils/constants.dart
Labels: gssoc, level2

#121 solved issue #120 and #136
  assets/images/quiz.jpg
  lib/main.dart
  lib/pages/about.dart
  lib/pages/explore.dart
  lib/pages/explore/quiz.dart
  lib/pages/favorite.dart
  lib/pages/home.dart
  lib/pages/modules/colours.dart
  lib/pages/modules/flowers.dart
  lib/pages/modules/parts.dart
  lib/pages/modules/planets.dart
  lib/pages/modules/seasons.dart
  lib/utils/constants.dart
Labels: gssoc, level1

#140 Dependabot Added
  .github/workflows/dependabot.yaml
Labels: gssoc

#149 BottomNavFixwithPageTransition
  lib/landing_page.dart
  lib/main.dart
  lib/pages/home.dart
  lib/pages/main_home.dart
  lib/utils/route/page_transtion.dart
  lib/utils/route/route_constant.dart
  lib/utils/route/routes.dart
  lib/widgets/drawer.dart
  web/favicon.png
  web/icons/Icon-maskable-192.png
  web/icons/Icon-maskable-512.png
Labels: gssoc, level1
