Repository VaibhavCodeClub/learn, pull requests merged in 2024-06, with the labels that each got.

#176 listed all the flowers
  lib/pages/explore/quiz.dart
  lib/pages/modules/colours.dart
  lib/pages/modules/flowers.dart
  lib/pages/modules/planets.dart
  lib/utils/assets_path.dart
Labels: gssoc

#183 Update README.md
  README.md
Labels: VSoC’24, 1-POINT

#184 removed unused imports and fixed WidgetSateProperty errors
  lib/pages/fruits.dart
  lib/pages/home.dart
  lib/pages/modules/atoz.dart
  lib/pages/modules/seasons.dart
  lib/widgets/drawer.dart
Labels: VSoC’24, EASY

#188 the getting started page now appears only once in the app's lifetime
  lib/landing_page.dart
  lib/main.dart
  pubspec.yaml
Labels: VSoC’24, EASY

#190 Errors resolved in running of app
  android/gradle/wrapper/gradle-wrapper.properties
  lib/main.dart
  lib/pages/explore/drawingboard.dart
  lib/pages/explore/explore.dart
  lib/pages/fruits.dart
  lib/pages/home.dart
  lib/pages/main_home.dart
  lib/pages/modules/animals.dart
  lib/pages/modules/animals_test.dart
  lib/pages/modules/atoz.dart
  lib/pages/modules/birds.dart
  lib/pages/modules/birds_test.dart
  lib/pages/modules/colours.dart
  lib/pages/modules/flowers.dart
  lib/pages/modules/flowers_test.dart
  lib/pages/modules/occupation.dart
  lib/pages/modules/occupations_test.dart
  lib/pages/modules/parts.dart
  lib/pages/modules/parts_test.dart
  lib/pages/modules/planets.dart
  lib/pages/modules/planets_test.dart
  lib/pages/modules/seasons.dart
  lib/utils/assets_path.dart
  lib/utils/route/route_constant.dart
  lib/utils/route/routes.dart
  lib/widgets/drawer.dart
Labels: gssoc, level3

#191 Add Animated Page Transitions for Bottom Navigation Tabs
  lib/pages/main_home.dart
  lib/widgets/navbar/navbar.dart
Labels: gssoc, level1
